# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[zh]
  languageCode = "zh-Hans"
  contentDir = "content/zh"
  title = "BMD-lab"
  [zh.params]
    description = "BMD-lab"
    email = "leeburton@tauex.tau.ac.il"
    phone = "+972 03-6409915"
    address = "Department of Materials Science and Engineering, The Iby and Aladar Fleischman Faculty of Engineering, Tel Aviv University, Tel Aviv 6997801, Israel"
    office_hours = "9:00 - 17:00 GMT+2"
    donate = "[给我们买咖啡](donate)"
  [[zh.menu.main]]
    name = "人"
    url = "#people"
    weight = 1
  [[zh.menu.main]]
    name = "新闻"
    url = "#news"
    weight = 2
  [[zh.menu.main]]
    name = "论文"
    url = "#featured"
    weight = 3
  [[zh.menu.main]]
    name = "联系"
    url = "#contact"
    weight = 4
  [[zh.menu.main]]
    name = "文档"
    url = "resources"
    weight = 5
