# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[he]
  languageCode = "he"
  contentDir = "content/he"
  title = "BMD-lab"
  [he.params]
    description = "BMD-lab"
    email = "leeburton@tauex.tau.ac.il"
    phone = "+972 03-6407872"
    address = "Department of Materials Science and Engineering, The Iby and Aladar Fleischman Faculty of Engineering, Tel Aviv University, Tel Aviv 6997801, Israel"
    office_hours = "9:00 - 17:00 GMT+2"
    donate = "[לקנות לנו קפה](donate)"
  [[he.menu.main]]
    name = "אֲנָשִׁים"
    url = "#people"
    weight = 1
  [[he.menu.main]]
    name = "חֲדָשׁוֹת"
    url = "#news"
    weight = 2
  [[he.menu.main]]
    name = "מומלצים"
    url = "#featured"
    weight = 3
  [[he.menu.main]]
    name = "איש קשר"
    url = "#contact"
    weight = 4
  [[he.menu.main]]
    name = "אֶמְצָעִי"
    url = "resources"
    weight = 5
